services:
  db:
    image: postgres:17-alpine
    container_name: task_app_dbms
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_app_db
    ports:
      - "54322:5432"
